### ISSUE TITLE
Nuget Packages

### ISSUE THREAD

**Issue by arri-cc** [duosecurity/duo_dotnet#1]
Can you provide/maintain a Nuget package for this?

**Comment by JayQuerido** [comment]
I know this is a year old... and it's disconcerting that nobody has replied, but there really should be a NuGet package for this. 
Having a current package often becomes a deciding factor when I'm evaluating options. Since this project seems to be half-dead, I'm not sure I can assume that there's a library for DuoSecurity...

**Comment by MoMoNge** [comment]
Can you assist to send additional parameters -email and group name?

**Comment by davidluxford** [comment]
Greetings arri-cc.  Thankyou for the feedback.  I apologize for the delay in responding to the NuGet issue.  Yes, I agree that a NuGet posting would be useful.  I'll add that to our roadmap for Windows.  I can't make a date commitment right now, but if anyone is interested, I'll let you know once we've figured that out.

**Comment by davidluxford** [comment]
MoMoNge, can you clarify your question?  Which endpoint are you calling, and can you post code showing what you're doing?

**Comment by MoMoNge** [comment]
In SingRequest Method , pass  security key ,integration key and username parameters!
_"public static string SignRequest(string skey, string ikey, string username)"
Want to pass additional parameters, email and group name, 
When user register in Duo 2FA, want to keep email and group name as well.

**Comment by davidluxford** [comment]
SignRequest is used only generate the signature for communication to the
service.  I think what you're asking is can you have a couple of parameters
sent back to you in the postback from our server.  If that's what you want,
then just declare a form with the id "duo_form" on the same page where the
init call is made.  We'll automatically send any fields in this form in the
auth request and then will return them in the postbackn response.  For an
example, please see "Passing additional POST arguments in the response" at
https://www.duosecurity.com/docs/duoweb.  If this isn't what you meant,
please let us know.

_David Luxford_
/ Senior Software Engineer

davidluxford@duosecurity.com

duosecurity.com

**Comment by memark** [comment]
How are things going with the Nuget package?

**Comment by davidluxford** [comment]
It's in the queue and is largely done, but I can't give a timeline on
release yet.

On Thursday, April 23, 2015, Magnus Markling notifications@github.com
wrote:

> How are things going with the Nuget package?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/duosecurity/duo_dotnet/issues/1#issuecomment-95455678
> .

## 

_David Luxford_
/ Senior Software Engineer

davidluxford@duosecurity.com

DuoSecurity.com https://duosecurity.com/

Better Security, Not Just More.

**Comment by memark** [comment]
Can I help out?

**Comment by davidluxford** [comment]
Possibly.  Let me work it out and I'll get back to you.  There is a lot
going on this week and next, so it may be two-three weeks.

David L-

On Thursday, April 23, 2015, Magnus Markling notifications@github.com
wrote:

> Can I help out?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/duosecurity/duo_dotnet/issues/1#issuecomment-95596638
> .

## 

_David Luxford_
/ Senior Software Engineer

davidluxford@duosecurity.com

DuoSecurity.com https://duosecurity.com/

Better Security, Not Just More.

**Comment by billHaggerty** [comment]
Link to nuget package?

**Comment by FLGMwt** [comment]
Hi! Just curious, where is this at? Our team is happy to help out on this and get an official nuget release out.

Anyone still maintaining this on the Duo side?

**Comment by DuoKristina** [comment]
There is a deceptively significant amount of work involved with getting this repo into a package, and it's not on the roadmap right now. When that changes we'll update this issue.

Thank you for your interest and for using Duo!

**Comment by JustinTCook** [comment]
@DuoKristina Is there any update on the nuget package? It seems back in 2015 it was in the queue and largely done, but as of Jan 10th, 2018, it is not on the roadmap.

**Comment by AaronAtDuo** [comment]
@JustinTCook I'm sorry to say that this is still not on the roadmap of planned work, and we don't have any estimate on when we may prioritize this.

**Comment by halllo** [comment]
This is really important to us! We would literally pay for a nuget package using dotnet standard.

**Comment by russharding** [comment]
Any word on that nuget package?

**Comment by AaronAtDuo** [comment]
Duo has released an updated library for integrating Duo into .NET web applications.  It is available on Github at https://github.com/duosecurity/duo_universal_csharp and on NuGet at https://www.nuget.org/packages/DuoUniversal.

Duo strongly recommends migrating web applications to the new prompt experience.   Therefore we will not be publishing this package (duo_dotnet) to NuGet.

See https://duo.com/docs/universal-prompt-update-guide for more information on the move to the Universal Prompt.  See https://github.com/duosecurity/duo_python/pull/57 for a step-by-step example of migrating a simple web application to the new prompt flow.

If you have any problems or issues using the new .NET package, please contact Duo support via https://duo.com/support, or open an issue at https://github.com/duosecurity/duo_universal_csharp.
