### ISSUE TITLE
The iframe is not doing a POST back, it's a GET

### ISSUE THREAD

**Issue by mwladika** [duosecurity/duo_dotnet#2]
The iframe is not doing a POST back, it's a GET and there's no sig_response.  

I am working with Visual Studio, .net 4.5, duo_dotnet, Duo-Web-v2.min.js (I've tried v1 too)

I also have to wonder why the demo reads the whole stream instead of dealing with a run of the mill post back.  I don't think that's too much to ask.

**Comment by ghost** [comment]
Hi Mark, we'll take a look at this - thanks for using Duo!
