### ISSUE TITLE
What are DUO_EXPIRE & APP_EXPIRE constants for ?

### ISSUE THREAD

**Issue by jernejg** [duosecurity/duo_dotnet#3]
Hi guys, I'm wondering who can provide a little bit more information about this two constants.

https://github.com/duosecurity/duo_dotnet/blob/aaf3f3734253f2d616850ca2ad0f88e51960bb6a/DuoWeb/DuoWeb.cs#L25

https://github.com/duosecurity/duo_dotnet/blob/aaf3f3734253f2d616850ca2ad0f88e51960bb6a/DuoWeb/DuoWeb.cs#L26

Is APP_EXPIRE the recommended way to define the expiration for the session after the user is logged with Duo ?

Thanks

**Comment by tsullyo** [comment]
Hi @jernejg!

The constants that you're asking about are used as part of our signing and verification. 

DUO_EXPIRE says that the signed authenticate request expires 5 minutes from now. So the browser has 5 minutes to send that request to Duo (assuming the local server's time is about the same as Duo's service's time.)

APP_EXPIRE is for the app_sig expiration, calculated locally. app_sig is used by your application to correlate the 2fa response with the 2fa request.

Duo handles the MFA step of the authentication flow, but does not control anything regarding the actual login session. As such, we have nothing to do with, and no control over, how long the application's sessions last. Such a thing would need to be configured as part of the application itself. 

Thanks for using Duo!

**Comment by tsullyo** [comment]
Quick follow up:  While altering the values of DUO_EXPIRE or APP_EXPIRE will not result in the behavior you're asking about, we also recommend against changing either of them.
