### ISSUE TITLE
dotnetcore2.0 support?

### ISSUE THREAD

**Issue by billHaggerty** [duosecurity/duo_dotnet#5]
Is there any support for 2fa outside of using the full framework? I need to use this product on a site that will be hosted on a linux server and uses dotnetcore 2 and aspnetcore 2. The DuoWeb project does not seem to be compatible with dotnetcore2.0.

**Comment by DuoKristina** [comment]
Sorry, not at this time. We're tracking this request to port duo_dotnet to dotnetcore internally now.

Thanks for trying Duo!

**Comment by kellcomnet2** [comment]
Any update on this project? I am in the same situation as @billHaggerty .

**Comment by billHaggerty** [comment]
If I remember correctly I just copied code in duoweb into a dotnet standard project and built it there. There wasn't any compatibility issues.

**Comment by dcb99** [comment]
Would be good to have .NET core support

**Comment by kellcomnet2** [comment]
FYI it does work perfectly with .net core.

just take the .net source and add it as classes, while it would be nice to have an official package.

**Comment by dcb99** [comment]
Can confirm this works by just added the classes to a .NET core project, but yes, it would be nice to have as a package.

**Comment by halllo** [comment]
dotnet standard would be the way to go for the nuget package. #1

**Comment by russharding** [comment]
Would love to see a package, and timelines? Happy to help....

**Comment by AaronAtDuo** [comment]
Duo has released an updated library for integrating Duo into .NET web applications.  It is available on Github at https://github.com/duosecurity/duo_universal_csharp and on NuGet at https://www.nuget.org/packages/DuoUniversal.

Duo strongly recommends migrating web applications to the new prompt experience.   The new package is targeted at netstandard2.0 and is intended to support all .NET application developers.

See https://duo.com/docs/universal-prompt-update-guide for more information on the move to the Universal Prompt.  See https://github.com/duosecurity/duo_python/pull/57 for a step-by-step example of migrating a simple web application to the new prompt flow.

If you have any problems or issues using the new .NET package, please contact Duo support via https://duo.com/support, or open an issue at https://github.com/duosecurity/duo_universal_csharp.
