### ISSUE TITLE
How to bypass the iframe and send direct push?

### ISSUE THREAD

**Issue by ghost** [duosecurity/duo_dotnet#8]
Hello guys,

Thank you for great documentation. we are doing the integration with our IOT device and need to bypass the iframe and send direct push after recognizing the username. 

Please provide some guidance on how to achieve this in duo web SDK javascript code.

Thank you in advance.

**Comment by AaronAtDuo** [comment]
@KWIKalamzoo Please let me know if the below is helpful to you, or it I'm misunderstanding your question.

If the iframe isn't going to be feasible, I think you next best bet is a direct API integration.  You'll want to look into using the Duo Auth API (https://duo.com/docs/authapi) which is available for all editions.

We have a C# client library available on github (https://github.com/duosecurity/duo_api_csharp) if that's useful to you.  If you have your own API calling code, it should be pretty easy to use it with the Auth API; for the most part it's a simple JSON-based API.  The only tricky bit is the authentication header.  The docs describe it very well, and our API client repos have code examples.

Thanks for using Duo!

Aaron

**Comment by ghost** [comment]
Hello Aaron,

Yes, our requirement is to send duo push after they authenticate to our embedded IOT device, for ex access control reader. 

I will start exploring the auth APIs and continue our integration. Greatly appreciates your quick response.
